### ISSUE TITLE
Add instructions to README for when pip can't find the matching distribution of WTPython

### ISSUE THREAD

**Issue by Shom770** [what-the-python/wtpython#118]
A few people have been having problems installing wtpython because wtpython is 3.9.x and above, I saw the other issues regarding allowing wtpython to work for earlier versions, but for now there should be an update to the README.md regarding what to do when you come across that error, for Linux/WSL and Mac

**Comment by VagishVela** [comment]
I think this will be resolved with testing, as in #120.

**Comment by Shom770** [comment]
> I think this will be resolved with testing, as in #120.

Yep, I'll close this issue then
