### ISSUE TITLE
Using [@click] feature

### ISSUE THREAD

**Issue by Shom770** [what-the-python/wtpython#123]
The @click feature allows text to be clickable, and run a function when clicked, so something like ``[@click 'func_name(args)'] Clickable Text [/]``, WTPython could use this feature for the sidebar with the other answers, instead of key binds to go to the other questions. This would make the UI/UX much nicer to work with.

**Comment by briancohan** [comment]
If possible, this should also apply to the answer headers in the main view. Link to the specific answer rather than just the question. Though they keystroke will probably have to be just the question page.
