### ISSUE TITLE
Enable scrolling of left sidebar, as right now you can select question/answers that are beyond the sidebar

### ISSUE THREAD

**Issue by VagishVela** [what-the-python/wtpython#128]
**Describe the bug**
You have to expand the terminal to see more questions on the sidebar, and with the keys you can go beyond the ones displayed

**To Reproduce**
1. Run `wtpython example/print_int_str_error.py`
2. Use right arrow key to go beyond the questions displayed in the terminal

**Expected behavior**
The list of questions should be scrollable or scroll with so you can see the active one.

**Screenshots**
Question selected is off the screen:
<img width="1340" alt="Screen Shot 2021-08-19 at 10 30 59 AM" src="https://user-images.githubusercontent.com/7334882/130087396-9a31debd-13d6-4bc6-855f-f6ed94d6e442.png">

Question selected is shown if you expand terminal:
<img width="1345" alt="Screen Shot 2021-08-19 at 10 31 09 AM" src="https://user-images.githubusercontent.com/7334882/130087477-c10ac2fd-46ec-43d8-b92a-c2ac7da9d2e9.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 11.4 Silicon

**Comment by briancohan** [comment]
Yeah, this has been a bug since day 1. Though I'm glad you made an issue for it.
