### ISSUE TITLE
Print traceback before proceeding to search for answers

### ISSUE THREAD

**Issue by briancohan** [what-the-python/wtpython#53]
In the main loop, we should probably print the full traceback (before going to stackoverflow) to the terminal so that they still get the stack trace even if our logic crashes. This would also allow the traceback to be visible if they exit the application.

**Comment by mustafaquraish** [comment]
Well the workflow in my mind is that:

1. User runs their program through `python`, and sees the exception / traceback
2. User then runs the program through `pytui`.

So in reality they will already have the traceback on their terminal beforehand. We should add the ability to show the traceback inside the user interface in a separate panel (I believe @ethansocal was showing this during a code standup?). That would be more useful IMO

**Comment by briancohan** [comment]
In my mind, if you call our app in lieu of `python` and there are no errors, then you should not see anything different. With the slight exception that we could use `rich.print` to make it look nicer.
