### ISSUE TITLE
Leave a "thank you" message in the terminal for the user once they exit

### ISSUE THREAD

**Issue by briancohan** [what-the-python/wtpython#54]
This is a small detail that doesn't impact much, but hopefully makes the user feel good about using our product.

Right before we call `Display().run()`, we should print out a nicely formatted "thank you for using rich" kind of message and invite them to check in on the project or where to reach us if there was a bug. The app will pop up and they'll do what they need, but when they exit, they'll see a message from us.

**Comment by mustafaquraish** [comment]
Maybe just a personal opinion, but seems a bit cheesy. I'd get annoyed real fast if a program I used all the time said "Thank you" in the terminal after. There's something nice about having a clean slate and you're right back to the original state once the program is done running.

**Comment by briancohan** [comment]
You bring up a good point. I think the first few times would be nice, but after a while it could get annoying. I was thinking it would be nice if there was a way to say "hey, if you found a bug, let us know." I don't  think a single line at the end would be too terrible, but maybe it should be functional if we do have one.

I was thinking it would be "cute" for the judges if we left them a little message. Perhaps we could have cli flags to enable/disable showing the message and storing the state of their preference in the same place where we cache search results.

```
Thanks for using  WTPython, blah blah blah

Leave a note on github or join our discord yada yada yada

Run "wtpython -Q" to permanently disable this message or "wtpython --thanks" to see this message in the future.
```

**Comment by mustafaquraish** [comment]
We can have an "info" window show up if they run `pytui` without any script name / have it be an extra panel in the footer which they can open. I like the more opt-in approach
